### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by simonsan** [rust-unofficial/patterns#345]
Comprehensive Rust has developed a nice translation mechanism for mdbook books: https://github.com/google/comprehensive-rust/blob/main/TRANSLATIONS.md

We could make some research on how to adapt to that workflow making it possible to translate `Rust patterns` to different languages.

[Newer simplified Chinese](https://github.com/rust-unofficial/patterns/issues/292) could be the starter.

**Comment by mgeisler** [comment]
Hi @simonsan, I would love to see the infrastructure used elsewhere. We will eventually publish the i18n helpers (https://github.com/google/comprehensive-rust/issues/462), but for now I recommend installing them with

```shell
cargo install --git https://github.com/google/comprehensive-rust i18n-helpers
```

**Comment by mgeisler** [comment]
> as it seems like that Markdown formatting isn't transferred in the translation process. Afaiu that could destroy the ability to further translate things within a language, when we would reformat the original markdown.

You are correct: the Markdown text is copied as-is to the PO files. So if you mass-format it, the translations will stop working.

My work arounds for this are:

- Implement https://github.com/google/mdbook-i18n-helpers/issues/19 that you linked above (harder)
- Implement a small tool which will apply formatting to the `msgid` entries in the PO files (much easier)

I hope to write a tool for the second option soon since I plan to standardize the formatting of my own Markdown files.

**Comment by mgeisler** [comment]
Maybe I should clarify that the mdbook-i18n-helpers extract the text on a per-paragraph basis right now. So changes only invalidate a single paragraph at a time.

If you add/remove a few words in a paragraph, Gettext will do a good job at finding the old paragraph when you update your `xx.po` file for the `xx` language. The entry is then marked "fuzzy", which is a signal to the translator that they need to update the old translation.
