### ISSUE TITLE
Deny warnings page is out of date

### ISSUE THREAD

**Issue by mvertescher** [rust-unofficial/patterns#89]
The [deny warnings page](https://github.com/rust-unofficial/patterns/blob/master/anti_patterns/deny-warnings.md) is a little out of date and should be updated to remove warnings that are no longer relevant.

**Comment by simonsan** [comment]
I wonder if it might be a better approach instead of listing single warnings that could be `safe to deny` (which will probably change more often in the future as well), to point to `rustc -W help` and let people pick the warnings they want to deny from that list by themselves. With the mindset: "If you want to deny single warnings please be responsible and pick yourself. We give you a recommendation which `allowed lint checks` might make sense to deny as well.

Also we could name `lint groups` provided by rustc rather than single lints.

Thoughts?
